channels:
  - nvidia
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.3.7
  - aiohttp=3.10.4
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - appdirs=1.4.4
  - archspec=0.2.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bedtools=2.31.1
  - biopython=1.84
  - blas=1.0=mkl
  - bleach=6.1.0
  - boltons=24.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - colorful=0.5.6
  - comm=0.2.2
  - conda=24.5.0
  - conda-libmamba-solver=24.7.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - contourpy=1.2.1
  - cryptography=43.0.0
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - cycler=0.12.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distlib=0.3.8
  - distro=1.9.0
  - elfutils=0.191
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - filelock=3.15.4
  - fmt=10.2.1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozendict=2.4.4
  - frozenlist=1.4.1
  - fsspec=2024.6.1
  - gdown=5.2.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.8.7
  - google-api-core=2.19.1
  - google-auth=2.33.0
  - googleapis-common-protos=1.63.2
  - grpcio=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - htslib=1.20
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=8.1.0
  - importlib_resources=6.4.0
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.1.8
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.4
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcurand=10.3.6.82
  - libcurl=8.8.0
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libmicrohttpd=1.0.1
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libparquet=17.0.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsolv=0.7.30
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lightning=2.4.0
  - lightning-utilities=0.11.6
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - memray=1.13.4
  - menuinst=2.1.1
  - mistune=3.0.2
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - munkres=1.0.7
  - mysql-connector-c=6.1.11
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.2.1
  - nodejs=22.6.0
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - numpy=2.0.0
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - overrides=7.7.0
  - p11-kit=0.24.1
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-spy=0.3.14
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.9
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-lightning=2.4.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - ray-core=2.33.0
  - ray-default=2.33.0
  - ray-tune=2.33.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.19.0
  - rsa=4.9
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.4.17
  - samtools=1.20
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setproctitle=1.3.3
  - setuptools=71.0.4
  - six=1.16.0
  - smart_open=7.0.4
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - sympy=1.13.0
  - tbb=2021.12.0
  - tensorboardx=2.6.2.2
  - terminado=0.18.1
  - textual=0.76.0
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchmetrics=1.4.0.post0
  - torchtriton=3.0.0
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucsc-bigwigtobedgraph=448
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - virtualenv=20.4.7
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=3.6.7
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
